# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificação')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'amostra',
                'verbose_name_plural': 'amostras',
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
