# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificação')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'evento',
                'ordering': ['id'],
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-timestamp', '-id'], name='v1_event_timesta_7bd4b8_idx'),
        ),
    ]
