# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:45
from __future__ import unicode_literals

from django.db import migrations

from v1.tasks import create_event_mapping


def event_index_mapping(apps, schema_editor):
    create_event_mapping()


class Migration(migrations.Migration):
    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(event_index_mapping)
    ]
